language: rust

sudo: required

# Dependencies of kcov
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
      - libiberty-dev

matrix:
  include:
    - rust: stable
    - rust: 1.19.0
    - rust: nightly
  allow_failures:
    - rust: nightly

script:
  - |
      cargo test --verbose
after_success:
  - |
    if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
      tar xzf master.tar.gz &&
      cd kcov-master &&
      mkdir build &&
      cd build &&
      cmake .. &&
      make &&
      cd ../.. &&
      for file in target/debug/yenc-*[^\.d]; do
        ./kcov-master/build/src/kcov --exclude-pattern=/.cargo,/usr/lib --verify --coveralls-id="$TRAVIS_JOB_ID" target/kcov "$file"
      done
    fi
