language: rust

sudo: false

# Dependencies of kcov, used for cargo-travis
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

matrix:
  include:
    - rust: stable
    - rust: 1.13.0
    - rust: nightly
  allow_failures:
    - rust: nightly

before_script:
  - |
    if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo install --force cargo-travis
      export PATH=$HOME/.cargo/bin:$PATH
    fi

script:
  - |
      cargo test --all --verbose

after_success:
  - |
    if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo coveralls --all
    fi
