sudo: false
language: rust
# for kcov
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libbfd-dev
      - binutils-dev
      - cmake 
    sources:
      - kalakris-cmake

rust:
  - nightly
  - beta
  - stable
  - 1.13.0
matrix:
  allow_failures:
    - rust: nightly

before_script:
  - |
      cargo install --force cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH

# main build
script:
  - |
      cargo build &&
      cargo test 

after_success:
  - cargo coveralls
