language: rust

sudo: false

matrix:
  include:
    - rust: stable
    - rust: 1.13.0
    - rust: nightly
  allow_failures:
    - rust: nightly

script:
  - |
      cargo build && cargo test && cargo doc
